target = [
    'younger men',
    'hypochondriacs',
    'misogynists',
    'convicts',
    'the under-exploited',
    'dat ass',
    'embarassing dads',
    'your dickhead uncle',
    'deadly cyborg girl gangs',
    'corporate puppets',
    'disillusioned liberals',
    'ex-anarchists',
    'nudist lesbian bee-farms',
    'recovering Catholics',
    'authority manipulators',
    'holographic sociopaths',
    'tumblr users who misquote Sylvia Plath',
    'The Cloud',
    'NSA Agents',
    'celibate pedophiles',
    'closet transhumanists',
    'multiple lightning strike victims'
]

product = [
    'uncontrollable gas',
    'uncomfortable seats',
    'awkward moments',
    'a sandwich on fire',
    'piles of money',
    'marketing research',
    'mountains of cocaine',
    'blues dancing',
    'hashtag thicke',
    'very noisy intercourse',
    'Barack Obama',
    'poorly-timed erections',
    'secret second lives',
    'coupons for free oatmeal',
    'misunderstood microagressions',
    'polyamorous ex-girlfriends',
    'lower-ass pimples',
    'a spray can of something that seems to be both floor wax and a desert topping',
    'codename: shuttlecock',
    'augmented surreality',
    'simulacrum and simulations',
    'the hypermarket',
    'made up simplification of post-structuralism',
    'alcoholic monogamists',
    'Nice Guy Syndrome',
    'chronic fedora-wearing',
    'naked baby photos'
]

value = [
    'revitalize your sex life',
    'put you in touch with your inner child',
    'get you laid six feet under',
    'reduce your chances of being assassinated',
    'inflict facial hair',
    'cause guys and sports',
    'reinvent marketing',
    'put your inner child in touch with other inner children',
    'fund the tacocopter',
    'make you the high lord of Skyrim',
    'disappear the bad people',
    'sponge bathe you in antioxidants',
    'keep you from noticing the affair',
    'let you know the moment before you say something stupid',
    'keep you up to date on hip music',
    'literally keep you alive forever',
    'automatically update your tumblr',
    'posthumously update your LiveJournal',
    'send erotic emails to your crush',
    'remove the calories from the custard',
    'improve your bowling average',
    'finally help you appreciate baseball',
    'turn you invisible',
    'numb the unceasing cold ache in your heart'
]

other = [
    'zuul',
    'a wet ferret',
    'a urinary tract infection',
    'the laughter of children',
    'death and/or taxes',
    'a mumbled sales pitch',
    'an overbearing boss',
    'a bossy over-bear',
    'the ubermensch',
    'the CTO',
    'the ubermensch',
    'an angry poodle',
    'an entitled rich mom',
    'the huddled masses',
    'neurotic celebrities',
    'that one friend you feel weird about',
    'the one that got away',
    'poorly explained standardized testing instructions',
    'burnt-out arctic explorers'
]

benefit = [
    'the ladies love it',
    'the ladies hate it',
    'nine out of ten dictators recommend it',
    "I'm not just a user, I'm also a dealer",
    'of cancerous side-effects',
    'of the unthinkable alternative',
    'you envy my social status',
    'hashtag yoloswag, hashtag twerking',
    'you asked for consent first',
    'of an unplaceable nostalgia',
    'Hitler. Always Hitler',
    'the howling emptiness of your soul needs to be fed',
    'of misdirected anger at teenagers',
    'of relating a bit too much than you should to a Kafka novel',
    'bros will worship at your gilded feet',
    'your mom will finally see you as an adult',
    'your dad will admit he needs therapy',
    "the kid that bullied you will admit they've loved you all these years"
]
